type 'a t = 'a BsOakVirtualDom.Virtual_dom.Attribute.t

(* regular attributes *)

val accent_height : string -> 'a t
val accelerate : string -> 'a t
val accumulate : string -> 'a t
val additive : string -> 'a t
val alphabetic : string -> 'a t
val allow_reorder : string -> 'a t
val amplitude : string -> 'a t
val arabic_form : string -> 'a t
val ascent : string -> 'a t
val attribute_name : string -> 'a t
val attribute_type : string -> 'a t
val auto_reverse : string -> 'a t
val azimuth : string -> 'a t
val base_frequency : string -> 'a t
val base_profile : string -> 'a t
val bbox : string -> 'a t
val begin' : string -> 'a t
val bias : string -> 'a t
val by : string -> 'a t
val calc_mode : string -> 'a t
val cap_height : string -> 'a t
val class' : string -> 'a t
val clip_path_units : string -> 'a t
val content_script_type : string -> 'a t
val content_style_type : string -> 'a t
val cx : string -> 'a t
val cy : string -> 'a t
val d : string -> 'a t
val decelerate : string -> 'a t
val descent : string -> 'a t
val diffuse_constant : string -> 'a t
val divisor : string -> 'a t
val dur : string -> 'a t
val dx : string -> 'a t
val dy : string -> 'a t
val edge_mode : string -> 'a t
val elevation : string -> 'a t
val end' : string -> 'a t
val exponent : string -> 'a t
val external_resources_required : string -> 'a t
val filter_res : string -> 'a t
val filter_units : string -> 'a t
val format : string -> 'a t
val from : string -> 'a t
val fx : string -> 'a t
val fy : string -> 'a t
val g1 : string -> 'a t
val g2 : string -> 'a t
val glyph_name : string -> 'a t
val glyph_ref : string -> 'a t
val gradient_transform : string -> 'a t
val gradient_units : string -> 'a t
val hanging : string -> 'a t
val height : string -> 'a t
val horiz_adv_x : string -> 'a t
val horiz_origin_x : string -> 'a t
val horiz_origin_y : string -> 'a t
val id : string -> 'a t
val ideographic : string -> 'a t
val in' : string -> 'a t
val in2 : string -> 'a t
val intercept : string -> 'a t
val k : string -> 'a t
val k1 : string -> 'a t
val k2 : string -> 'a t
val k3 : string -> 'a t
val k4 : string -> 'a t
val kernel_matrix : string -> 'a t
val kernel_unit_length : string -> 'a t
val key_points : string -> 'a t
val key_splines : string -> 'a t
val key_times : string -> 'a t
val lang : string -> 'a t
val length_adjust : string -> 'a t
val limiting_cone_angle : string -> 'a t
val local : string -> 'a t
val marker_height : string -> 'a t
val marker_units : string -> 'a t
val marker_width : string -> 'a t
val mask_content_units : string -> 'a t
val mask_units : string -> 'a t
val mathematical : string -> 'a t
val max : string -> 'a t
val media : string -> 'a t
val method' : string -> 'a t
val min : string -> 'a t
val mode : string -> 'a t
val name : string -> 'a t
val num_octaves : string -> 'a t
val offset : string -> 'a t
val operator : string -> 'a t
val order : string -> 'a t
val orient : string -> 'a t
val orientation : string -> 'a t
val origin : string -> 'a t
val overline_position : string -> 'a t
val overline_thickness : string -> 'a t
val panose1 : string -> 'a t
val path : string -> 'a t
val path_length : string -> 'a t
val pattern_content_units : string -> 'a t
val pattern_transform : string -> 'a t
val pattern_units : string -> 'a t
val point_order : string -> 'a t
val points : string -> 'a t
val points_at_x : string -> 'a t
val points_at_y : string -> 'a t
val points_at_z : string -> 'a t
val preserve_alpha : string -> 'a t
val preserve_aspect_ratio : string -> 'a t
val primitive_units : string -> 'a t
val r : string -> 'a t
val radius : string -> 'a t
val ref_x : string -> 'a t
val ref_y : string -> 'a t
val rendering_intent : string -> 'a t
val repeat_count : string -> 'a t
val repeat_dur : string -> 'a t
val required_extensions : string -> 'a t
val required_features : string -> 'a t
val restart : string -> 'a t
val result : string -> 'a t
val rotate : string -> 'a t
val rx : string -> 'a t
val ry : string -> 'a t
val scale : string -> 'a t
val seed : string -> 'a t
val slope : string -> 'a t
val spacing : string -> 'a t
val specular_constant : string -> 'a t
val specular_exponent : string -> 'a t
val speed : string -> 'a t
val spread_method : string -> 'a t
val start_offset : string -> 'a t
val std_deviation : string -> 'a t
val stemh : string -> 'a t
val stemv : string -> 'a t
val stitch_tiles : string -> 'a t
val strikethrough_position : string -> 'a t
val strikethrough_thickness : string -> 'a t
val string' : string -> 'a t
val style : string -> 'a t
val surface_scale : string -> 'a t
val system_language : string -> 'a t
val table_values : string -> 'a t
val target : string -> 'a t
val target_x : string -> 'a t
val target_y : string -> 'a t
val text_length : string -> 'a t
val title : string -> 'a t
val to' : string -> 'a t
val transform : string -> 'a t
val type' : string -> 'a t
val u1 : string -> 'a t
val u2 : string -> 'a t
val underline_position : string -> 'a t
val underline_thickness : string -> 'a t
val unicode : string -> 'a t
val unicode_range : string -> 'a t
val units_per_em : string -> 'a t
val v_alphabetic : string -> 'a t
val v_hanging : string -> 'a t
val v_ideographic : string -> 'a t
val v_mathematical : string -> 'a t
val values : string -> 'a t
val version : string -> 'a t
val vert_adv_y : string -> 'a t
val vert_origin_x : string -> 'a t
val vert_origin_y : string -> 'a t
val view_box : string -> 'a t
val view_target : string -> 'a t
val width : string -> 'a t
val widths : string -> 'a t
val x : string -> 'a t
val x_height : string -> 'a t
val x1 : string -> 'a t
val x2 : string -> 'a t
val x_channel_selector : string -> 'a t
val xlink_actuate : string -> 'a t
val xlink_arcrole : string -> 'a t
val xlink_href : string -> 'a t
val xlink_role : string -> 'a t
val xlink_show : string -> 'a t
val xlink_title : string -> 'a t
val xlink_type : string -> 'a t
val xml_base : string -> 'a t
val xml_lang : string -> 'a t
val xml_space : string -> 'a t
val y : string -> 'a t
val y1 : string -> 'a t
val y2 : string -> 'a t
val y_channel_selector : string -> 'a t
val z : string -> 'a t
val zoom_and_pan : string -> 'a t

(* presentation attributes *)

val alignment_baseline : string -> 'a t
val baseline_shift : string -> 'a t
val clip_path : string -> 'a t
val clip_rule : string -> 'a t
val clip : string -> 'a t
val color_interpolation_filters : string -> 'a t
val color_interpolation : string -> 'a t
val color_profile : string -> 'a t
val color_rendering : string -> 'a t
val color : string -> 'a t
val cursor : string -> 'a t
val direction : string -> 'a t
val display : string -> 'a t
val dominant_baseline : string -> 'a t
val enable_background : string -> 'a t
val fill_opacity : string -> 'a t
val fill_rule : string -> 'a t
val fill : string -> 'a t
val filter : string -> 'a t
val flood_color : string -> 'a t
val flood_opacity : string -> 'a t
val font_family : string -> 'a t
val font_size_adjust : string -> 'a t
val font_size : string -> 'a t
val font_stretch : string -> 'a t
val font_style : string -> 'a t
val font_variant : string -> 'a t
val font_weight : string -> 'a t
val glyph_orientation_horizontal : string -> 'a t
val glyph_orientation_vertical : string -> 'a t
val image_rendering : string -> 'a t
val kerning : string -> 'a t
val letter_spacing : string -> 'a t
val lighting_color : string -> 'a t
val marker_end : string -> 'a t
val marker_mid : string -> 'a t
val marker_start : string -> 'a t
val mask : string -> 'a t
val opacity : string -> 'a t
val overflow : string -> 'a t
val pointer_events : string -> 'a t
val shape_rendering : string -> 'a t
val stop_color : string -> 'a t
val stop_opacity : string -> 'a t
val stroke_dasharray : string -> 'a t
val stroke_dashoffset : string -> 'a t
val stroke_linecap : string -> 'a t
val stroke_linejoin : string -> 'a t
val stroke_miterlimit : string -> 'a t
val stroke_opacity : string -> 'a t
val stroke_width : string -> 'a t
val stroke : string -> 'a t
val text_anchor : string -> 'a t
val text_decoration : string -> 'a t
val text_rendering : string -> 'a t
val unicode_bidi : string -> 'a t
val visibility : string -> 'a t
val word_spacing : string -> 'a t
val writing_mode : string -> 'a t

(* events - mouse *)

val on_click : 'a -> 'a t
val on_mouse_down : 'a -> 'a t
val on_mouse_up : 'a -> 'a t
val on_mouse_over : 'a -> 'a t
val on_mouse_out : 'a -> 'a t

(* events - custom *)

val on : string -> 'a BsOakJson.Decode.decoder -> 'a t
val prevent_default_on : string -> ('a * bool) BsOakJson.Decode.decoder -> 'a t
val stop_propagation_on : string -> ('a * bool) BsOakJson.Decode.decoder -> 'a t
val custom : string -> 'a BsOakVirtualDom.Virtual_dom.Attribute.options BsOakJson.Decode.decoder -> 'a t